### ISSUE TITLE
ch2 code on oreily.com book is wildly different

### ISSUE THREAD

**Issue by letto4135** [PacktPublishing/Flutter-Projects#13]
For one the code in the book does not work. 
RenderBox was not laid out: _RenderSingleChildViewport#aa1ea relayoutBoundary=up8 NEEDS-PAINT
At the end of the "completing the ui" step it has you wrap most of the project in a SingleChildScrollView which causes the error.

There is no mention of any of these variables
double sizeX = MediaQuery.of(context).size.width;
double sizeY = MediaQuery.of(context).size.height;
final spacer = Padding(padding: EdgeInsets.only(bottom: sizeY/40));

And Spacer() is used instead of spacer....

How are you going to have the initial commit of the repo be this different from the book? Seems like quite the oversite.

**Comment by letto4135** [comment]
Also, when you do implement sizeX and sizeY with MaterialApp wrapping MyApp you get yet another error so even this repo doesn't work.
No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of()

**Comment by shubham763** [comment]
Hi @letto4135 

The author explained the code lines in the book and some code were missing as you mentioned. The author has explained those code line in later chapters. I'll recommend you to use the GitHub repo's code and refer book for the explanation, for a better result. 

Thanks!
