### ISSUE TITLE
code outdated as of late 2021

### ISSUE THREAD

**Issue by ulisinn** [PacktPublishing/Flutter-Projects#15]
I wish the lifespan of the book would be extended by at least keeping the example code up-to-date.
Or stop selling the book.

**Comment by binsoopark** [comment]
If you tell me which part is the problem, I will try to correct the error or keep the code up-to-date. Thank you for your opinion.

**Comment by nithikpackt** [comment]
Hi, we have contacted the author for an update. Will let you know once we have the info.
