### ISSUE TITLE
Chapter 6, Flutter type 'List<ShoppingList>' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by imamtarique** [PacktPublishing/Flutter-Projects#6]
Here is my getList function:

Future<List<ShoppingList>> getLists() async {
    final List<Map<String, dynamic>> maps = await db.query('lists');
    // ignore: missing_return
    return List.generate(maps.length, (i) {
      return ShoppingList(
        maps[i]['id'],
        maps[i]['name'],
        maps[i]['priority'],
      );
    });
  }

I am calling it from here 
showData() async {
    dynamic bb;
    await helper.openDb();
    shoppingList = await helper.getLists();
    
  setState(() {
shoppingList=shoppingList;
});
  }
}

I am getting the error 

type 'List<ShoppingList>' is not a subtype of type 'int'

**Comment by simoales** [comment]
Hi @imamtarique ,

How did you declare shoppingList? From the error you mention it seems shoppingList is declared as **int**, while getLists() returns a Future of type List. So shoppingList should be declared as "List": like

`List shoppingList = List(); `

Hope this helps
