### ISSUE TITLE
Ch 7: runtime error in EventDetails.fromMap constructor

### ISSUE THREAD

**Issue by elstepherino** [PacktPublishing/Flutter-Projects#7]
It seems that the error originates here:

EventDetail.fromMap( dynamic obj ) {
    this.id = obj['id'];  // <<<< CRASH
    this._description = obj['description'];
    this._date = obj['date'];
    this._startTime = obj['start_time'];
    this._endTime = obj['end_time'];
    this._speaker = obj['speaker'];
    this._isFavorite = obj['is_favourite'];
}

Not sure why this is happening.  Any ideas?

Thanks.

Here is the stack trace:

/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Class 'QueryDocumentSnapshot' has no instance method '[]'.
    Receiver: Instance of 'QueryDocumentSnapshot'
    Tried calling: []("id")
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      new EventDetail.fromMap (package:events/models/event_detail.dart:14:18)
    #2      _EventListState.getDetailsList.<anonymous closure> (package:events/screens/event_screen.dart:60:54)
    #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
    #5      new List.from (dart:core-patch/array_patch.dart:38:29)
    #6      new List.of (dart:core-patch/array_patch.dart:68:17)
    #7      ListIterable.toList (dart:_internal/iterable.dart:211:44)
    #8      _EventListState.getDetailsList (package:events/screens/event_screen.dart:60:66)
    <asynchronous suspension>
    #9      _EventListState.initState (package:events/screens/event_screen.dart:31:7)
    #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
    #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #31     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
    #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
    #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
    #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #41     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #43     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)

**Comment by elstepherino** [comment]
It seems that in this statement: 
`var data = await db.collection('event_details').get();`

data is now a QueryDocumentSnapshot...

**Comment by AnujPundir29** [comment]
> It seems that the error originates here:
> 
> EventDetail.fromMap( dynamic obj ) {
> this.id = obj['id']; // <<<< CRASH
> this._description = obj['description'];
> this._date = obj['date'];
> this._startTime = obj['start_time'];
> this._endTime = obj['end_time'];
> this._speaker = obj['speaker'];
> this._isFavorite = obj['is_favourite'];
> }
> 
> Not sure why this is happening. Any ideas?
> 
> Thanks.
> 
> Here is the stack trace:
> 
> /flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: Class 'QueryDocumentSnapshot' has no instance method '[]'.
> Receiver: Instance of 'QueryDocumentSnapshot'
> Tried calling:
> #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1 new EventDetail.fromMap (package:events/models/event_detail.dart:14:18)
> #2 _EventListState.getDetailsList. (package:events/screens/event_screen.dart:60:54)
> #3 MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
> #4 ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
> #5 new List.from (dart:core-patch/array_patch.dart:38:29)
> #6 new List.of (dart:core-patch/array_patch.dart:68:17)
> #7 ListIterable.toList (dart:_internal/iterable.dart:211:44)
> #8 _EventListState.getDetailsList (package:events/screens/event_screen.dart:60:66)
> 
> #9 _EventListState.initState (package:events/screens/event_screen.dart:31:7)
> #10 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
> #11 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
> #12 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #13 Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
> #14 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
> #15 Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
> #16 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
> #17 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
> #18 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #19 Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
> #20 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
> #21 Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
> #22 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
> #23 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
> #24 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #25 Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
> #26 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
> #27 Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
> #28 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
> #29 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
> #30 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #31 MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
> #32 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #33 Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
> #34 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
> #35 StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
> #36 Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
> #37 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
> #38 StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
> #39 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
> #40 Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
> #41 Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
> #42 ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
> #43 Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
> #44 ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
> #45 ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)

Hey I am getting this error can you tell me what with code....

E/flutter (24002): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
E/flutter (24002): Receiver: null
E/flutter (24002): Tried calling: map(Closure: (dynamic) => Movie)
[38;5;244mE/flutter (24002): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5))[39;49m
[38;5;248mE/flutter (24002): #1      HttpHelper.getUpcoming[39;49m 
 package:movies/http_helper.dart
E/flutter (24002): <asynchronous suspension>
[38;5;248mE/flutter (24002): #2      _MovieListState.initialize[39;49m 
 package:movies/movie_list.dart
[38;5;248mE/flutter (24002): #3      _MovieListState.initState[39;49m 
 package:movies/movie_list.dart
[38;5;244mE/flutter (24002): #4      StatefulElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #5      ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #6      Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #7      Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #8      ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #9      Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #10     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #11     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #12     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #13     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #14     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #15     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #16     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #17     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #18     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #19     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #20     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #21     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #22     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #23     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #24     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #25     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #26     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #27     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #28     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #29     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #30     StatefulElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #31     Element.rebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #32     ComponentElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #33     StatefulElement._firstBuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #34     ComponentElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #35     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #36     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #37     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #38     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #39     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #40     SingleChildRenderObjectElement.mount[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #41     Element.inflateWidget[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #42     Element.updateChild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #43     ComponentElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
[38;5;244mE/flutter (24002): #44     StatefulElement.performRebuild[39;49m 
 package:flutter/…/widgets/framework.dart
E/flutter (24002): #45     Element.rebuild (package:f
I/Choreographer(24002): Skipped 1 frames!  The application may be doing too much work on its main thread.
Application finished.
Exited (sigterm)
