### ISSUE TITLE
Unhandled Exception: Bad state: field does not exist within the DocumentSnapshotPlatform

### ISSUE THREAD

**Issue by gangov** [PacktPublishing/Flutter-Projects#9]
This is the database in Firestore: [link](https://drive.google.com/file/d/1QJoRZOZXb4phrpPjgYddGyJMgg8tERRw/view?usp=sharing) as you can see it is exactly as it's needed;

However upon running the application from chapter 7 on "The EventDetails model class" we get 
Unhandled Exception: Bad state: field does not exist within the DocumentSnapshotPlatform error message.

The error is caused because there's a missing field 'id' in our FireStore database, but we're trying to assign it from the EventDetail.fromMap named constructor

This needs to be updated, as we as a lot of deprecated code lines, such as getDocuments() (in favor of get()), documents() (in favor of docs()) etc;

**Comment by deepesh-packt** [comment]
Hey @gangov ,
the project currently only supports up to Flutter 1.12.

**Comment by Shaban-ali** [comment]
yes gangov thank you i solved it by your comment it was spell mistake it was not matching with firestore ids so i change name as in firestore in my code and its work now
